name: Run Unit Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Run Tests
      run: |
        cd src
        pwd
        dotnet test -l "console;verbosity=detailed"
