name: Run Unit Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Run Tests
      run: dotnet test -l "console;verbosity=detailed" src/Sudoku.Tests/Sudoku.Tests.csproj
